mysite_deploy/blogapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    MainView,
    ArticleListView,
    ArticleCreateView,
    ArticleViewSet,
    ArticleDetailView,
    LatestArticlesFeed,

)

app_name = "blogapp"

routers = DefaultRouter()
routers.register('articles', ArticleViewSet)


urlpatterns = [
    path("", MainView.as_view(), name="main_view"),
    path("articles/create/", ArticleCreateView.as_view(), name="article_create"),
    path("articles/", ArticleListView.as_view(), name="article_list"),
    path("articles/<int:pk>/", ArticleDetailView.as_view(), name="article-detail"),
    path("articles/latest/feed/", LatestArticlesFeed(), name="article-feed")
    # path('api/', include(routers.urls))
]

mysite_deploy/mysite_deploy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from .sitemaps import sitemaps

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('blog/', include('blogapp.urls')),

    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap',
    ),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls'))
    )

mysite_deploy/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
# from django.views.decorators.cache import cache_page

from .views import (
    ShopIndexView,
    groups_list,
    get_cookie_view,
    #products_list,
    #orders_list,
    OrderListView,
    UserOrdersListView,
    OrderDetailView,
    OrderCreateView,
    OrderUpdateView,
    OrderDeleteView,
    OrdersDataExportView,
    ProductDetailView,
    ProductsListView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ProductsDataExportView,
    LatestProductsFeed,
    MainView,
    ShopLoginView,
    ShopLogoutView,
    AboutUserView,
    RegisterUserView,
    GroupsListViewGeneric,
    ProductViewSet,
    OrderViewSet
)

app_name = "shopapp"

routers = DefaultRouter()
routers.register('products', ProductViewSet)
routers.register('orders', OrderViewSet)

urlpatterns = [
    path("cookie/get/", get_cookie_view, name="main_view"),
    # path("index/", cache_page(60*3)(ShopIndexView.as_view()), name="index"),
    path("index/", ShopIndexView.as_view(), name="index"),
    path("", MainView.as_view(), name="main_view"),
    path("groups/", groups_list, name="groups_list"),
    #path("products/", products_list, name="products_list"),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="products_detail"),
    path("products/<int:pk>/update-product/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/archive/", ProductDeleteView.as_view(), name="product_archive"),
    path("products/export/", ProductsDataExportView.as_view(), name="products_export"),
    path("products/latest/feed/", LatestProductsFeed(), name="product-feed"),
    #path("orders/", orders_list, name="orders_list"),
    path("orders/", OrderListView.as_view(), name="orders_list"),
    path('users/<int:user_id>/orders/', UserOrdersListView.as_view(), name="user_orders_list"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="orders_detail"),
    path("orders/<int:pk>/update-order/", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/archive/", OrderDeleteView.as_view(), name="order_delete"),
    path("users/<int:user_id>/orders/export/", OrdersDataExportView.as_view(), name="orders_export"),
    path('login/', ShopLoginView.as_view(), name='login_form'),
    path('logout/', ShopLogoutView.as_view(), name='logout_form'),
    path('about-user/', AboutUserView.as_view(), name='about_user'),
    path('register-user/', RegisterUserView.as_view(), name='register_user'),
    path('groups-generic/', GroupsListViewGeneric.as_view(), name='groups-generic'),
    path('api/', include(routers.urls))
]

mysite_deploy/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


def product_preview_directory_path_new(instance: "Product", name: str) -> str:
    return 'products/product_{pk}/preview/{filename}'.format(pk=instance.name, filename=name)


class Product(models.Model):
    """
    Модель Product представляет товар, который можно продавать в интернет магазине.

    Заказы тут: :model:`shopapp.Order`
    """

    class Meta:
        ordering = ["name", "price"]

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path_new)

    def __str__(self):
        return f"Product(pk={self.pk}, name={self.name!r})"

    def get_absolute_url(self):
        return reverse('shopapp:products_detail', kwargs={'pk': self.pk})


class Order(models.Model):
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")
    receipt = models.FileField(null=True, blank=True, upload_to='orders/receipts')


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)

mysite_deploy/shopapp/forms.py
from django import forms
from django.forms import ModelForm
from .models import Product


# class ProductForm(ModelForm):
#     def __init__(self, *args, **kwargs):
#         self.is_authenticated = kwargs.pop('is_authenticated')
#         super().__init__(*args, **kwargs)
#
#     class Meta:
#         model = Product
#         fields = ['name', 'description', 'price']

class AuthForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

mysite_deploy/shopapp/views.py
"""
В этом модуле лежат различные наборы представлений.

Разные view интернет магазина: по товарам, заказам и т.д.
"""

import logging

from random import random

from csv import DictWriter

from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group, User
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from timeit import default_timer

from django.contrib.auth.models import Group
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.syndication.views import Feed
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView, TemplateView

from rest_framework.decorators import api_view, action
from rest_framework.response import Response
from rest_framework.request import Request
from rest_framework.views import APIView
from rest_framework.generics import GenericAPIView, ListCreateAPIView
from rest_framework.mixins import ListModelMixin
from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.parsers import MultiPartParser

from .serializers import GroupSerializer, ProductSerializer, OrderSerializer

from drf_spectacular.utils import extend_schema, OpenApiResponse

from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
from django.core.cache import cache

from .models import Product, Order, Profile
from .common import save_csv_products

# log = logging.getLogger(__name__)


class ShopIndexView(View):
    # @method_decorator(cache_page(60 * 2))
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 1999),
            ('Desktop', 2999),
            ('Smartphone', 999),
        ]
        context = {
            "time_running": default_timer(),
            "products": products,
        }
        # log.debug('Products for shop index %s', products)
        # log.info('Rendering shop index')
        print('shop index contex', context)
        return render(request, 'shopapp/shop-index.html', context=context)


@cache_page(60 * 2)
def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get('fizz', 'default value')
    return HttpResponse(f'Cookie value: {value!r} + {random()}')


def groups_list(request: HttpRequest):
    context = {
        "groups": Group.objects.prefetch_related('permissions').all(),
    }
    return render(request, 'shopapp/groups-list.html', context=context)


# def products_list(request: HttpRequest):
#     context = {
#         "products": Product.objects.all(),
#     }
#     return render(request, 'shopapp/products-list.html', context=context)

# def orders_list(request: HttpRequest):
#     context = {
#         "orders": Order.objects.select_related("user").prefetch_related("products").all(),
#     }
#     return render(request, 'shopapp/orders-list.html', context=context)

class OrderListView(LoginRequiredMixin, ListView):
    queryset = (
        Order.objects
            .select_related("user")
            .prefetch_related("products")
    )
    # template_name = 'shopapp/order_list.html'
    # model = Order
    # context_object_name = 'object_list'


class UserOrdersListView(LoginRequiredMixin, ListView):
    template_name = 'shopapp/order_list_user.html'
    model = Order
    owner = None

    def get_queryset(self):
        user_id = self.kwargs.get('user_id')
        self.owner = get_object_or_404(User, pk=user_id)
        return super().get_queryset().filter(user=self.owner)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['owner'] = self.owner
        return context


class OrderDetailView(PermissionRequiredMixin, DetailView):
    permission_required = ['view_order']
    template_name = 'shopapp/orders-detail.html'
    model = Order
    context_object_name = 'order'


class OrderCreateView(CreateView):
    model = Order
    fields = ['user', 'delivery_address', 'products', 'promocode', 'receipt']
    success_url = reverse_lazy('shopapp:orders_list')


class OrderUpdateView(UpdateView):
    model = Order
    fields = ['user', 'delivery_address', 'products', 'promocode', 'receipt']
    # template_name = 'order_update_form'
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse(
            'shopapp:orders_detail',
            kwargs={'pk': self.object.pk},
        )


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy('shopapp:orders_list')


# class OrderDetailView(View):
#     def get(self, request: HttpRequest, pk: int) -> HttpResponse:
#         order = get_object_or_404(Order, pk=pk)
#         context = {
#             'order': order
#         }
#         return render(request, 'shopapp/products-detail.html', context=context)

class OrdersDataExportView(View):

    def get(self, request: HttpRequest, user_id) -> JsonResponse:
        owner = get_object_or_404(User, id=user_id)
        cache_key = f'orders_data_user_id:{user_id}>export'
        orders_data = cache.get(cache_key)
        if orders_data is None:
            orders = Order.objects.order_by('pk').filter(user=owner)
            orders_data = [
                {
                    'user': order.user.username,
                    'delivery_address': order.delivery_address,
                    'promocode': order.promocode,
                    'created_at': order.created_at,
                    'products': [product.name for product in order.products.all()],
                }
                for order in orders
            ]
            cache.set(cache_key, orders_data, 180)
        return JsonResponse({'orders': orders_data})


class ProductsListView(ListView):
    template_name = 'shopapp/products-list.html'
    # model = Product
    queryset = Product.objects.filter(
        archived=False
    )  # Для того чтобы в списке отображались только объекты с archived=False
    context_object_name = 'products'


class ProductsDataExportView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        cache_key = 'products_data>export'
        products_data = cache.get(cache_key)
        if products_data is None:
            products = Product.objects.order_by('pk').all()
            products_data = [
                {
                    'pk': product.pk,
                    'name': product.name,
                    'price': product.price,
                    'archived': product.archived,
                }
                for product in products
            ]
            cache.set(cache_key, products_data, 300)
        elem = products_data[0]
        name = elem['name']
        print('nsme:', name)
        return JsonResponse({'products': products_data})


# class ProductDetailView(View):
#     def get(self, request: HttpRequest, pk: int) -> HttpResponse:
#         product = get_object_or_404(Product, pk=pk)
#         context = {
#             'product': product
#         }
#         return render(request, 'shopapp/products-detail.html', context=context)

class ProductDetailView(DetailView):
    template_name = 'shopapp/products-detail.html'
    model = Product
    context_object_name = 'product'


class ProductCreateView(UserPassesTestMixin, CreateView):
    def test_func(self):
        # return self.request.user.groups.filter(name='secret-group').exists() # проверка на существование пользователя в группе
        return self.request.user.is_superuser

    model = Product
    fields = ['name', 'price', 'description', 'discount', 'preview']
    success_url = reverse_lazy('shopapp:products_list')


class ProductUpdateView(UpdateView):
    model = Product
    fields = ['name', 'price', 'description', 'discount', 'preview']
    # template_name = либо указать имя шаблона либо имя суффикса ниже
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse(
            'shopapp:products_detail',
            kwargs={'pk': self.object.pk},
        )


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('shopapp:products_list')

    def form_valid(self, form):  # данный метод переопределяет удаление и делает его не полным
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class LatestProductsFeed(Feed):
    title = 'Products (latest)'
    description = 'Updates on changes and addition products'
    link = reverse_lazy('shopapp:products_list')

    def items(self):
        return (
            Product.objects.filter(archived=False)
                .order_by('-created_at')[:5]
        )

    def item_title(self, item: Product):
        return item.name

    def item_description(self, item: Product):
        return item.description[:200]


class MainView(View):  # переход на главную страницу после авторизации на ShopLoginView
    def get(self, request):
        return render(request, 'shopapp/base.html')


class ShopLoginView(LoginView):
    template_name = 'shopapp/login.html'
    redirect_authenticated_user = True


class ShopLogoutView(LogoutView):
    template_name = 'shopapp/logout.html'


class AboutUserView(TemplateView):
    template_name = 'shopapp/about-user.html'


class RegisterUserView(CreateView):
    form_class = UserCreationForm
    template_name = 'shopapp/register.html'
    success_url = reverse_lazy('shopapp:about_user')

    def form_valid(self, form):
        response = super().form_valid(form)

mysite_deploy/shopapp/templates/shopapp/about-user.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    About User
{% endblock %}

{% block body %}
<div>
    <h1>User Info</h1>
    <div>Products available: {% now 'u' %}</div>
    {% if request.user.is_authenticated %}
        {% cache 300 userinfo user.username %}
            <h2>Detail</h2>
            <p>Username: {{ user.username }}</p>
            <p>Firstname: {{ user.first_name }}</p>
            <p>Lastname: {{ user.last_name }}</p>
            <p>Email: {{ user.email }}</p>
            <p>Bio: {{user.profile.bio}}</p>
            {% if perms.shopapp.view_order %}
                <p>Permissions: {{ perms.shopapp }}</p>
            {% endif %}
        {% endcache %}
        <div>
            <a href="{% url 'shopapp:products_list' %}">To products list</a>
        </div>
        <div>
            <a href="{% url 'shopapp:orders_list' %}">To orders list</a>
        </div>
        <div>
            <a href="{% url 'shopapp:main_view' %}">Back to main page</a>
        </div>
        <br>
        <div>
            <a href="{% url 'shopapp:logout_form' %}">Logout</a>
        </div>
        <br>
    {% else %}
        <h2>You are not authorised User is anonymous</h2>
        <div>
            <a href="{% url 'shopapp:login_form' %}">Login</a>
        </div>
        <div>
            <a href="{% url 'shopapp:main_view' %}">Back to main page</a>
        </div>
    {% endif %}
</div>
{% endblock %}

mysite_deploy/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
      Base Title
    {% endblock %}
  </title>
</head>
<body>
    {% block body %}
        <div>
            {% if request.user.is_authenticated %}
                <h1>Welcome to the website</h1>
                <h2>I'm the main page</h2>
                <div>
                    <a href="{% url 'shopapp:products_list' %}">To products list</a>
                </div>
                <div>
                    <a href="{% url 'shopapp:orders_list' %}">To orders list</a>
                </div>
                <div>
                    <a href="{% url 'shopapp:about_user' %}">To user profile</a>
                </div>
                <br>
                <div>
                    <a href="{% url 'shopapp:logout_form' %}">Logout</a>
                </div>
                <br>
            {% else %}
                <h2>You are not authorised on our website</h2>
                <div>
                    <a href="{% url 'shopapp:login_form' %}">Login</a>
                </div>
            {% endif %}
        </div>
    {% endblock %}
</body>
</html>

mysite_deploy/shopapp/templates/shopapp/login.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
<div>
    <h2>Login page</h2>
    <form method="post">
        {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Login</button>
    </form>
</div>
<div>
    <a href="{% url 'shopapp:register_user' %}">Register user</a>
</div>
{% endblock %}

mysite_deploy/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}


{% block title %}
  Confirm archive {{object.name}}
{% endblock %}

{% block body %}
  <h1>Are you sure you want to delete {{object.name}}?</h1>
  <br>
  <div>
      <a href="{% url 'shopapp:orders_detail' pk=object.pk %}">Back to orders #{{ object.pk }}</a>
  </div>
  <br>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Delete</button>
  </form>
{% endblock %}

mysite_deploy/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Orders list
{% endblock %}

{% block body %}
  <h1>Orders:</h1>
  {% if object_list %}
    <div>
      {% for order in object_list %}
        <div>
          <p>Order by {% firstof order.user.first_name order.user.username %}</p>
          <p>Promocode: <code>{{ order.promocode }}</code></p>
          <p>Delivery address: {{ order.delivery_address }}</p>
          <a href="{% url 'shopapp:orders_detail' pk=order.pk %}">Detail order</a>
          <div>
            Product in order:
            <ul>
              {% for product in order.products.all %}
                <li>{{ product.name }} for ${{ product.price }}</li>
              {% endfor %}
            </ul>
          </div>

        </div>
      {% endfor %}

    </div>
  {% else %}
    <h3>No orders yet</h3>
  {% endif %}
  <div>
    <a href="{% url 'shopapp:order_create'%}">Create new order</a>
  </div>
  <div>
    <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
  </div>
{% endblock %}

mysite_deploy/shopapp/templates/shopapp/orders-detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Order detail №{{order.pk}}
{% endblock %}

{% block body %}
    <h1>Orders <strong>{{order.user}}</strong></h1>
    <div>
        <ul>
            <div>Product:</div>
            {% for product in order.products.all %}
            <li>{{ product.name }} for ${{ product.price }}</li>
            {% endfor %}
        </ul>
        <div>Promocode: {{order.promocode}}</div>
        <div>Created_at: {{order.created_at}}</div>
        <div>Archived: {{order.archived}}</div>
        {% if order.receipt %}
            <img src="{{order.receipt.url}}" alt="order.receipt.user">
        {% endif %}
    </div>
    <div>
       <a href="{% url 'shopapp:order_update' pk=order.pk %}">Update order</a>
    </div>
    <div>
       <a href="{% url 'shopapp:order_delete' pk=order.pk %}">Delete order</a>
    </div>
    <div>
        <a href="{% url 'shopapp:orders_list' %}">Back to orders list</a>
    </div>
{% endblock %}

mysite_deploy/shopapp/templates/shopapp/orders_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls  %}
    <li>
      <a href="{% url 'admin:import_orders_csv' %}" class="addlink">
        Import CSV
      </a>
    </li>
    {{ block.super }}
{% endblock %}

mysite_deploy/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}


{% block title %}
  Create product
{% endblock %}

{% block body %}
  <h1>Create product</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
  </form>
  <div>
      <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
  </div>
{% endblock %}

mysite_deploy/shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}


{% block title %}
  Update product
{% endblock %}

{% block body %}
  <h1>Update product</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
  </form>
  <div>
      <a href="{% url 'shopapp:products_detail' pk=object.pk %}">Back to products #{{ object.pk }}</a>
  </div>
{% endblock %}

mysite_deploy/shopapp/templates/shopapp/products-detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Product detail №{{product.pk}}
{% endblock %}

{% block body %}
    <h1>Product <strong>{{product.name}}</strong></h1>
    <div>
      <div>Description: <em>{{product.description}}</em></div>
      <div>Price: {{product.price}}</div>
      <div>Discount: {{product.discount}}</div>
      <div>Archived: {{product.archived}}</div>
      {% if product.preview %}
        <img src="{{product.preview.url}}" width="300" alt="product.preview.name">
      {% endif %}
    </div>
    <div>
       <a href="{% url 'shopapp:product_update' pk=product.pk %}">Update product</a>
    </div>
    <div>
       <a href="{% url 'shopapp:product_archive' pk=product.pk %}">Archive product</a>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
    </div>
{% endblock %}

mysite_deploy/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Products list
{% endblock %}

{% block body %}
  <h1>Products:</h1>
  {% if products %}
    <div>
    {% for product in products %}
      <div>
        <p><a href="{% url 'shopapp:products_detail' pk=product.pk %}">Name: {{ product.name }}</a></p>
        <p>Price: {{ product.price }}</p>
        <p>Discount: {% firstof product.discount 'no discount' %}</p>
      </div>
      {% if product.preview %}
      <img src="{{product.preview.url}}" width="300" alt="product.preview.name">
      {% endif %}
    {% endfor %}

    </div>

  {% else %}
    <h3>No products yet</h3>
  {% endif %}

  <div>
    <a href="{% url 'shopapp:product_create'%}">Create new product</a>
  </div>
  <div>
    <a href="{% url 'shopapp:orders_list' %}">Orders</a>
  </div>
  <div>
    <a href="{% url 'shopapp:main_view' %}">Back to main page</a>
  </div>
{% endblock %}

mysite_deploy/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls  %}
    <li>
      <a href="{% url 'admin:import_products_csv' %}" class="addlink">
        Import CSV
      </a>
    </li>
    {{ block.super }}
{% endblock %}

mysite_deploy/shopapp/templates/shopapp/register.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Register User
{% endblock %}

{% block body %}
<div>
    <h1>Register User</h1>
    <form method="post">
        {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" value="Register">Register</button>
    </form>
</div>
{% endblock %}

mysite_deploy/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
  Shop Index
{% endblock %}


{% block body %}
  <h1>Hello Shop Index!</h1>

  <div>
    <ul>
      {% for name, price in products %}
        <li>{{ name }} ({{ name|length }}) for ${{ price }}</li>
        {% if name|length_is:'7' %}
          <span>Lucky product!</span>
        {% endif %}
      {% empty %}
        No products here
      {% endfor %}

    </ul>
  </div>

  <div>
    Time running: {{ time_running }}
  </div>

  {% cache 100 lorem %}
    <div>
      {% lorem 3 p random %}
    </div>
  {% endcache %}

{% endblock %}