mysite_deploy/blogapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    MainView,
    ArticleListView,
    ArticleCreateView,
    ArticleViewSet,
    ArticleDetailView,
    LatestArticlesFeed,

)

app_name = "blogapp"

routers = DefaultRouter()
routers.register('articles', ArticleViewSet)


urlpatterns = [
    path("", MainView.as_view(), name="main_view"),
    path("articles/create/", ArticleCreateView.as_view(), name="article_create"),
    path("articles/", ArticleListView.as_view(), name="article_list"),
    path("articles/<int:pk>/", ArticleDetailView.as_view(), name="article-detail"),
    path("articles/latest/feed/", LatestArticlesFeed(), name="article-feed")
    # path('api/', include(routers.urls))
]

mysite_deploy/mysite_deploy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from .sitemaps import sitemaps

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('blog/', include('blogapp.urls')),

    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap',
    ),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls'))
    )

mysite_deploy/blogapp/models.py
from django.db import models


# Create your models here.
from django.urls import reverse


class Author(models.Model):
    """
    Модель Product представляет представляет автора статьи

    """
    name = models.CharField(max_length=100, db_index=True)
    bio = models.TextField(null=False, blank=True)

    def __str__(self):
        return f"Author(pk={self.pk}, name={self.name!r})"


class Category(models.Model):
    """
     Модель Category представляет категорию статьи

    """
    name = models.CharField(max_length=40, db_index=True)

    def __str__(self):
        return f"Category(pk={self.pk}, name={self.name!r})"


class Tag(models.Model):
    """
    Модель Tag представляет тэг, который можно назначить статье

    """
    name = models.CharField(max_length=20, db_index=True)

    def __str__(self):
        return f"Tag(pk={self.pk}, name={self.name!r})"


class Article(models.Model):
    """
    Модель Article представляет представляет статью

    """

    class Meta:
        ordering = ["title", "author"]

    title = models.CharField(max_length=200, db_index=True)
    content = models.TextField(null=False, blank=True)
    pub_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return f"Article(pk={self.pk}, title={self.title}, author{self.author!r})"

    def get_absolute_url(self):
        return reverse('blogapp:article-detail', kwargs={'pk': self.pk})

mysite_deploy/blogapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.syndication.views import Feed
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, CreateView, DetailView
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import extend_schema, OpenApiResponse
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.viewsets import ModelViewSet

from blogapp.models import Article

from blogapp.serializers import ArticleSerializer


class MainView(View):  # переход на главную страницу после авторизации на ShopLoginView
    def get(self, request):
        return render(request, 'blogapp/base.html')


class ArticleListView(LoginRequiredMixin, ListView):
    queryset = (
        Article.objects.filter(pub_date__isnull=False)
            .order_by('-pub_date')
            .defer('content')
            .select_related("author")
            .prefetch_related("tags")
    )

class ArticleDetailView(DetailView):
    model = Article

class LatestArticlesFeed(Feed):
    title = 'Blog articles (latest)'
    description = 'Updates on changes and addition blog articles'
    link = reverse_lazy('blogapp:article_list')

    def items(self):
        return(
        Article.objects.filter(pub_date__isnull=False)
            .order_by('-pub_date')
            .defer('content')
            .select_related("author")
            .prefetch_related("tags")[:5]
        )

    def item_title(self, item: Article):
        return item.title

    def item_description(self, item: Article):
        return item.content[:200]

    # def item_link(self, item: Article):
    #     return reverse('blogapp:article-detail', kwargs={'pk': item.pk})

class ArticleCreateView(CreateView):
    model = Article
    fields = ['title', 'content', 'author', 'category', 'tags']
    success_url = reverse_lazy('blogapp:article_list')


@extend_schema(description="Article views CRUD")
class ArticleViewSet(ModelViewSet):
    """
    Набор представлений для действий над Article
    Полный CRUD для сущеностей статей
    """
    queryset = Article.objects.all()
    serializer_class = ArticleSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = ['title', 'author']
    filterset_fields = [
        'title',
        'content',
        'author',
        'category',
    ]
    ordering_fields = [
        'title',
        'author',
        'category',
    ]

    @extend_schema(
        summary='Get one article by ID',
        description='Retrieves **article**, returns 404 if not found',
        responses={
            200: ArticleSerializer,
            404: OpenApiResponse(description='Empty response, article by id not found'),
        }
    )
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)

mysite_deploy/blogapp/templates/blogapp/article_detail.html
{% extends 'blogapp/base.html' %}

{% block title %}
  Article detail №{{article.pk}}
{% endblock %}

{% block body %}
   <h1>Article <strong>{{article.title}}</strong></h1>
    <div>
      <div>Content: <em>{{article.content}}</em></div>
      <p>Pub-date: {{article.pub_date}}</p>
      <p>Article by {{article.author.name}}</p>
      <p>Category: {{ article.category.name }}</p>
    </div>
    <div>
        <a href="{% url 'blogapp:article_list' %}">Back to articles list</a>
    </div>
{% endblock %}

mysite_deploy/blogapp/templates/blogapp/article_form.html
{% extends 'blogapp/base.html' %}


{% block title %}
  Create article
{% endblock %}

{% block body %}
  <h1>Create article</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
  </form>
  <div>
      <a href="{% url 'blogapp:article_list' %}">Back to articles list</a>
  </div>
{% endblock %}

mysite_deploy/blogapp/templates/blogapp/article_list.html
{% extends 'blogapp/base.html' %}

{% block title %}
  Article list
{% endblock %}

{% block body %}
  <h1>Articles:</h1>
  {% if object_list %}
    <div>
      {% for article in object_list %}
        <div>
          <p>Title: <a href="{% url 'blogapp:article-detail' pk=article.pk %}">{{ article.title }}</a></p>
          <p>Pub-date: {{article.pub_date}}</p>
          <p>Article by {{article.author.name}}</p>
          <p>Category: {{ article.category.name }}</p>
          <div>
            Tags in article:
            <ul>
              {% for tag in article.tags.all %}
                <li>Tags: {{tag.name }}</li>
              {% endfor %}
            </ul>
          </div>

        </div>
      {% endfor %}

    </div>
  {% else %}
    <h3>No articles yet</h3>
  {% endif %}
  <div>
    <a href="{% url 'blogapp:article_create'%}">Create new article</a>
  </div>
  <div>
    <a href="{% url 'blogapp:main_view' %}">Back to main-page</a>
  </div>
{% endblock %}

mysite_deploy/blogapp/templates/blogapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
      Base Title
    {% endblock %}
  </title>
</head>
<body>
    {% block body %}
        <div>
            <h1>Welcome to the website</h1>
            <h2>I'm the main page</h2>
            <div>
                <a href="{% url 'blogapp:article_list' %}">To article list</a>
            </div>
        </div>
    {% endblock %}
</body>
</html>